# Generated by Django 4.1.1 on 2022-09-07 22:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyClubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='User First Name')),
                ('last_name', models.CharField(max_length=64, verbose_name='User Last Name')),
                ('email', models.EmailField(max_length=64, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=128, verbose_name='Venue Address')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Venue Zip Code')),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('web', models.URLField(verbose_name='Website Address')),
                ('email', models.EmailField(max_length=64, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Event Name')),
                ('date', models.DateTimeField(verbose_name='Event Date')),
                ('manager', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('attendees', models.ManyToManyField(blank=True, to='events.myclubuser')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.venue')),
            ],
        ),
    ]
